---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install prerequisite packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
    state: present

- name: Add Jenkins repository key
  apt_key:
    url: "{{ jenkins_repo }}"
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: "deb http://pkg.jenkins.io/debian-stable binary/"
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Start and enable Jenkins service
  systemd:
    name: jenkins
    enabled: yes
    state: started

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Add Jenkins user to Docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Install Git
  apt:
    name: git
    state: present

- name: Verify Jenkins installation
  shell: |
    curl -fsSL http://localhost:8080 || (echo "Jenkins not responding!" && exit 1)
  ignore_errors: yes
