- name: Configure Jenkins Server
  hosts: jenkins_server  # Matches the group in inventory.ini
  become: true
  tasks:
    - name: Ensure Jenkins is installed
      apt:
        name: jenkins
        state: present
      tags: jenkins
